spring.application.name=notification-service
server.port=5005
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:notification_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
jwt.expiration=86400000
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Eureka client configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-registry:8761/eureka}
eureka.instance.prefer-ip-address=true

# RabbitMQ configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# RabbitMQ exchange and queue configuration
app.rabbitmq.exchange=${RABBITMQ_EXCHANGE:task.events}
app.rabbitmq.queue.task-assigned=task.assigned.queue
app.rabbitmq.queue.task-comment-created=task.comment.created.queue
app.rabbitmq.queue.project-invitation-created=project.invitation.created.queue
app.rabbitmq.routing-key.task-assigned=task.assigned
app.rabbitmq.routing-key.task-comment-created=task.comment.created
app.rabbitmq.routing-key.project-invitation-created=project.invitation.created
