spring.application.name=notification-service
server.port=5005
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notification_db}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:mypassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=5000
jwt.expiration=86400000

spring.profiles.active=local
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# RabbitMQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ exchange and queue configuration
app.rabbitmq.exchange=task.events
app.rabbitmq.queue.task-assigned=task.assigned.queue
app.rabbitmq.queue.task-comment-created=task.comment.created.queue
app.rabbitmq.queue.project-invitation-created=project.invitation.created.queue
app.rabbitmq.routing-key.task-assigned=task.assigned
app.rabbitmq.routing-key.task-comment-created=task.comment.created
app.rabbitmq.routing-key.project-invitation-created=project.invitation.created