spring.application.name=api-gateway
server.port=8765

# Enable Eureka Client (so gateway knows about services)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable automatic route creation based on service IDs
spring.cloud.gateway.discovery.locator.enabled=true

# (Optional) Make service IDs lower?case in routes ? default is as registered
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.profiles.active=local

# Service URLs for dashboard aggregation
services.project-service.url=http://project-service
services.task-service.url=http://task-service
services.user-service.url=http://user-service
services.sprint-service.url=http://sprint-service