<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sonhoang2</groupId>
    <artifactId>Task-Management-API</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Task Management Platform</name>
    <description>Parent project for Task Management microservices</description>

    <modules>
        <module>common-lib</module>
        <module>api-gateway</module>
        <module>service-registry</module>
        <module>user-service</module>
        <module>project-service</module>
        <module>task-service</module>
        <module>sprint-service</module>
        <module>notification-service</module>
        <module>dashboard-service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                    <configuration>
                        <source>21</source>
                        <target>21</target>
                        <release></release>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>