spring.application.name=user-service
server.port=5001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
jwt.expiration=604800000

spring.profiles.active=local
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG