spring.application.name=user-service
server.port=5001
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
jwt.expiration=86400000

server.servlet.context-path=/api/v1
spring.profiles.active=local
spring.jpa.properties.hibernate.jdbc.time_zone=UTC