spring.application.name=user-service
server.port=5001
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:user_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
jwt.expiration=604800000
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Eureka client configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-registry:8761/eureka}
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.security=${LOGGING_LEVEL_SPRING_SECURITY:DEBUG}
logging.level.org.springframework.web=${LOGGING_LEVEL_SPRING_WEB:DEBUG}
